name: CI

on:
  pull_request:
  push:

jobs:
  build_Linux:
    name: Build Windows/Linux
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          path: feature

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
          cache: sbt

      - name: Compile and Build JavaScript
        working-directory: feature
        run: sbt "compile" && sbt "compile/buildJavaScript"
